### ISSUE TITLE
Use Swimlanes with Trello Desktop App?

### ISSUE THREAD

**Issue by joshuarbholden** [jyaus/swimlanes-for-trello#9]
I'm using the Trello Desktop App (Windows) and I'd love to be able to use Swimlanes with it.  Any idea if that's possible or how?  Thanks!

----Josh

**Comment by jyaus** [comment]
Sorry, no -- it's a browser extension, so I don't know of any way to make it work with their desktop app.

**Comment by joshuarbholden** [comment]
Bummer!  Thanks for the reply.  It looks like Firefox is working on a webapp mode, so maybe I'll try that.
